name: VoidSweep
version: '${version}'
main: net.voidsweep.VoidSweep
api-version: '1.16'
authors: [Ilya Bush]
description: A flexible plugin to keep your server clean.
commands:
  vs:
    usage: /vs <subcommand>
permissions:
  voidsweep.command.clear:
    default: op
  voidsweep.command.reload:
    default: op
  voidsweep.command.autoclean.on:
    default: op
  voidsweep.command.autoclean.off:
    default: op
